
            <div class='cover'>
                <div class='inner stats' data-behaviour='cover_stats'>
                    <nav>
                        <ul>
                            <li><a href="/">All time</a></li>
                            <li><a href="/">This year</a></li>
                            <li><a href="/">This month</a></li>
                            <li class='active'><a href="/">This week</a></li>
                            <li><a href="/">Today</a></li>
                        </ul>
                    </nav>
                    <div class='period' data-period='all_time'>
                        <div class='money-earned'>
                            <span class='value'>5,100</span>
                            <span class='description'>Money earned</span>
                        </div>
                        <div class='hours-logged' data-minutes='360'>
                            <div class='value'>
                                <span class='hours'>6</span>
                                <span class='minutes'>00</span>
                            </div>
                            <span class='description'>Time logged</span>
                        </div>
                        <div class='active-projects'>
                            <span class='value'>1</span>
                            <span class='description'>Projects juggled</span>
                        </div>
                    </div>
                    <div class='period' data-period='this_year'>
                        <div class='money-earned'>
                            <span class='value'>5,100</span>
                            <span class='description'>Money earned</span>
                        </div>
                        <div class='hours-logged' data-minutes='360'>
                            <div class='value'>
                                <span class='hours'>6</span>
                                <span class='minutes'>00</span>
                            </div>
                            <span class='description'>Time logged</span>
                        </div>
                        <div class='active-projects'>
                            <span class='value'>1</span>
                            <span class='description'>Projects juggled</span>
                        </div>
                    </div>
                    <div class='period' data-period='this_month'>
                        <div class='money-earned'>
                            <span class='value'>0</span>
                            <span class='description'>Money earned</span>
                        </div>
                        <div class='hours-logged' data-minutes='0'>
                            <div class='value'>
                                <span class='hours'>0</span>
                                <span class='minutes'>00</span>
                            </div>
                            <span class='description'>Time logged</span>
                        </div>
                        <div class='active-projects'>
                            <span class='value'>0</span>
                            <span class='description'>Projects juggled</span>
                        </div>
                    </div>
                    <div class='active period' data-period='this_week'>
                        <div class='money-earned'>
                            <span class='value'>0</span>
                            <span class='description'>Money earned</span>
                        </div>
                        <div class='hours-logged' data-minutes='0'>
                            <div class='value'>
                                <span class='hours'>0</span>
                                <span class='minutes'>00</span>
                            </div>
                            <span class='description'>Time logged</span>
                        </div>
                        <div class='active-projects'>
                            <span class='value'>0</span>
                            <span class='description'>Projects juggled</span>
                        </div>
                    </div>
                    <div class='period' data-period='today'>
                        <div class='money-earned'>
                            <span class='value'>0</span>
                            <span class='description'>Money earned</span>
                        </div>
                        <div class='hours-logged' data-minutes='0'>
                            <div class='value'>
                                <span class='hours'>0</span>
                                <span class='minutes'>00</span>
                            </div>
                            <span class='description'>Time logged</span>
                        </div>
                        <div class='active-projects'>
                            <span class='value'>0</span>
                            <span class='description'>Projects juggled</span>
                        </div>
                    </div>
                </div>


            </div>
            <div class='container'>
                <div class='inner'>
                    <section class='page'>
                        <div class='page-header'>
                            <h1>Activity</h1>
                        </div>
                        <ol class='clock-24 entry-log' data-behaviour='entry_log' data-show='{"user":true,"time":true,"profit":true,"project":true,"comment":true,"billed":false}'>
                            <li data-date='2014-08-25'>
                                <h2>
                                    25 August
                                    <span class='day-of-the-week'>Monday</span>
                                </h2>
                                <ul class='entries'>
                                    <li class='entry' data-entry='{"id":32324,"minutes":360,"profit":5100.0,"date":"2014-08-25","billed":false}'>
                                        <div class='user'>
                                            <div class="avatar" size="small" title="Claus Hjort Bube"><span class="overlay"></span><img alt="F6ac6862baaffdcf62f4e0047007ddf9.png?d=https%3a%2f%2fdingapp static.s3.amazonaws.com%2favatar" src="https://secure.gravatar.com/avatar/f6ac6862baaffdcf62f4e0047007ddf9.png?d=https%3A%2F%2Fdingapp-static.s3.amazonaws.com%2Favatar.png&amp;r=PG&amp;s=80" /></div>
                                        </div>
                                        <div class='time-profit'>
                                            <div class='time'>
                                                6h 
                                            </div>
                                            <div class='profit'>
                                                5,100.00
                                            </div>
                                        </div>
                                        <div class='project'>
                                            <span class='client'>Lund Elmer Sandager</span>
                                            <a href="/clients/lund-elmer-sandager/projects/konsulentbistand">Konsulentbistand</a>
                                        </div>
                                        <div class='comment'>
                                            <span>Møde med EG</span>
                                        </div>
                                        <div class='actions' data-entry-dropdown=''>
                                            <a class='opener' data-opener='' href='#'>open</a>
                                            <div class='dropdown' data-dropdown-container=''>
                                                <ul>
                                                    <li>
                                                        <a data-mark-as-billed="" href="#">Mark as billed
                                                        </a></li>
                                                    <li><a data-edit-entry="" href="#">Edit</a></li>
                                                    <li><a data-delete-entry="" href="#">Delete</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li>
                            <li class='load-more'></li>
                        </ol>


                    </section>
                    <section class='time-tracker' data-time-tracker=''>
                        <div class='tab-bar' data-tab-switcher=''>
                            <a class='active' href='#'>Log time</a>
                            <a class='timer' href='#'>Timer</a>
                        </div>
                        <div class='tabs' data-tabs=''>
                            <div class='active log-time tab'>
                                <div class='form-wrapper' data-logger=''>
                                    <form accept-charset="UTF-8" action="/entries" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="iBVahSp7wwiAL/hPQBG1BVYPBkgi9P2uKmiJh0ARb9M=" /></div><div class='time-and-date'>
                                            <div class='time'>
                                                <input class="time" id="entry_time" name="entry[time]" tabindex="1" type="text" />
                                            </div>
                                            <div class='date' data-date-picker=''>
                                                <input id="entry_date" name="entry[date]" type="hidden" value="today" />
                                                <a class='opener' data-opener='' href='#' tabindex='2'>
                                                    <span data-label=''>Today</span>
                                                </a>
                                            </div>
                                        </div>
                                        <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"},{"id":5020,"name":"test","client":"test"}]'>
                                            <input data-id-field="" id="entry_project_id" name="entry[project_id]" type="hidden" value="5020" />
                                            <a class='opener' data-opener='' href='#'>
                                                <span class='client-name'>test</span>
                                                <span class='project-name'>test</span>
                                            </a>
                                        </div>

                                        <div class='comment'>
                                            <textarea data-behaviour="textarea_autogrow" id="entry_comment" name="entry[comment]" placeholder="Optional comment" tabindex="4">
                                            </textarea>
                                        </div>
                                        <div class='actions'>
                                            <button class="submit-button disabled" name="button" tabindex="5" type="submit">Log time</button>
                                        </div>
                                    </form>

                                </div>
                            </div>
                            <div class='tab timer' data-timer=''>
                                <div class='time'>
                                    <div class='elapsed-time' data-time-field=''>
                                        <span class='hours'>00</span>
                                        <span class='separator'>:</span>
                                        <span class='minutes'>00</span>
                                        <span class='separator'>:</span>
                                        <span class='seconds'>00</span>
                                    </div>
                                    <a class='play toggle-timer' data-toggle-timer='' href='#'></a>
                                </div>
                                <div class='spent-on'>
                                    <span>Spent working on</span>
                                </div>
                                <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"},{"id":5020,"name":"test","client":"test"}]'>
                                    <input data-id-field="" id="timer_project_id" name="timer_project_id" type="hidden" value="5020" />
                                    <a class='opener' data-opener='' href='#'>
                                        <span class='client-name'>test</span>
                                        <span class='project-name'>test</span>
                                    </a>
                                </div>

                                <div class='comment'>
                                    <textarea data-comment-field="" id="comment" name="comment" placeholder="Optional comment">
                                    </textarea>
                                </div>
                                <div class='actions'>
                                    <a class="button" data-delete="" href="#"><i class='icon-delete'></i>
                                    </a><a class="button" data-finish="" href="#"><i class='icon-finish'></i>
                                    </a></div>
                            </div>
                        </div>
                        <div class='notifications' data-time-tracker-notifications=''></div>
                    </section>

                </div>
            </div>