<!doctype html>
<html lang="da">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="InkassoPortal giver dig overblik">
        <meta name="author" content="Kalna">
        <meta name="viewport" content="width=device-width">

        <title>FormKit</title>

        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" />
        <![endif]-->
    </head>
    <body>
        <style id="global_dyn_style"></style>
        <div class="abs" id="wrapper">
            <div class="abs" id="desktop" data-wallpaper="Wasim_Muklashy_Photography_Yosemite_Tunnel_View_Wide_2880x1800.jpg">
                <!-- Content -->
                <div id="content">
                    <?php
                    if (file_exists(VIEWPARTPATH . $this->task . '.phtml')) {
                        include VIEWPARTPATH . $this->task . '.phtml';
                    } else {
                        include VIEWPARTPATH . 'NOT_FOUND.phtml';
                    }
                    ?>
                </div>
                <?php include 'menu.phtml'; ?>
                <?php //include 'toolbar.phtml'; ?>
            </div>
    </body>
</html>
