<?php

use KalnaBase\Utilities;
?>
<!--<body>-->
<!--    <nav-bar params="route: route"></nav-bar>
    <div id="page" class="container" data-bind="component: { name: route().page, params: route }"></div>-->
<body>
    <style id="global_dyn_style"></style>
    <div class="abs" id="wrapper">
        <div class="abs" id="desktop" data-wallpaper="Wasim_Muklashy_Photography_Yosemite_Tunnel_View_Wide_2880x1800.jpg">
            <!--            <a class="abs icon" style="left:20px;top:20px;" href="#dock_computer">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_computer.png'); ?>
                            Computer
                        </a>
                        <a class="abs icon" style="left:20px;top:100px;" href="#dock_drive">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_drive.png'); ?>
                            Hard Drive
                        </a>
                        <a class="abs icon" style="left:20px;top:180px;" href="#dock_disc">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_disc.png'); ?>
                            Audio CD
                        </a>
                        <a class="abs icon" style="left:20px;top:260px;" href="#dock_network">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_network.png'); ?>
                            Network
                        </a>-->
 
            <div class="abs" id="bar_top">
                <span class="float_right" id="clock"></span>
                <ul>
                    <li>
                        <a class="menu_trigger" href="#">Kalna FormKit</a>
                        <ul class="menu">
                            <li>
                                <a class="punkt" href="#dock_computer">Computer</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="menu_trigger" href="#">Rediger</a>
                        <ul class="menu">
                            <li>
                                <a class="punkt" href="#undo">Fortryd<span class="symbol">⌥⌘Z</span></a>
                            </li>
                            <li>
                                <a class="punkt" href="#redo">Gentag<span class="symbol">⇧⌥⌘Z</span></a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="menu_trigger" href="#">Opsætning</a>
                        <ul class="menu">
                            <li>
                                <a class="punkt" href="#dock_applikation">Applikation</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_modul">Modul<span class="symbol">⌥⌘⎋</span></a>
                            </li>
                            <li>
                                <a class="submenu_trigger" href="#">Data<span class="symbol">></span></a>
                                <ul class="submenu">
                                    <li>
                                        <a class="subpunkt" href="#dock_model">Model</a>
                                    </li>
                                    <li>
                                        <a class="subpunkt" href="#dock_kollektion">Kollektion</a>
                                    </li>
                                    <li>
                                        <a class="subpunkt" href="#dock_element">Element</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="submenu_trigger" href="#">Layout<span class="symbol">></span></a>
                                <ul class="submenu">
                                    <li>
                                        <a class="subpunkt" href="#dock_form">Form</a>
                                    </li>
                                    <li>
                                        <a class="subpunkt" href="#dock_blok">Blok</a>
                                    </li>
                                    <li>
                                        <a class="subpunkt" href="#dock_felt">Felt</a>
                                    </li>
                                    <li>
                                        <a class="subpunkt" href="#dock_resource">Resource</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="menu_trigger" href="#">System</a>
                        <ul class="menu">
                            <li>
                                <a class="punkt" href="#dock_FKSYS002">Datatyper</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_FKSYS001">Felttyper</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_FKSYS003">Bloktyper</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_egenskabtyper">Egenskabtyper</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_FKSYS004">TODO</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a class="menu_trigger" href="#">Hjælp</a>
                        <ul class="menu">
                            <li>
                                <a class="punkt" href="#dock_shortcuts">Tastaturgenveje</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_news">Nyheder i FormKit</a>
                            </li>
                            <li>
                                <a class="punkt" href="#dock_about">Om FormKit</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!--            <div class="abs" id="bar_tool">
                            <ul>
                                <li>
            
                                    <a class="abs toolmenu_trigger icon" href="#dock_computer">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_computer.png'); ?>
                                        Computer
                                    </a>
                                </li>
                                <li>
            
                                    <a class="abs toolmenu_trigger icon" href="#dock_computer">
            <?= Utilities\HTML::LoadImage('Icons/icon_32_computer.png'); ?>
                                        Computer
                                    </a>
                                </li>
                                <li>
                                    <a class="toolmenu_trigger" href="#">Opsætning</a>
                                </li>
                                <li>
                                    <a class="toolmenu_trigger" href="#">System</a>
                                </li>
                                <li>
                                    <a class="toolmenu_trigger" href="#">Hjælp</a>
                                </li>
                            </ul>
                        </div>-->
            <div class="abs" id="bar_bottom">
                <a class="float_left" href="#" id="show_desktop" title="Show Desktop">
                    <?= Utilities\HTML::LoadImage('Icons/icon_24_minimize.png'); ?>
                </a>
                <ul id="dock">
                    <li id="dock_FKSYS001">
                        <a href="#window_FKSYS001">
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_resize.png', 'Resize', 'resize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_minimize.png', 'Minimize', 'minimize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_tofront.png', 'To front', 'tofront_window'); ?>
                            Felttyper
                        </a>
                    </li>
                    <li id="dock_FKSYS002">
                        <a href="#window_FKSYS002">
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_resize.png', 'Resize', 'resize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_minimize.png', 'Minimize', 'minimize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_tofront.png', 'To front', 'tofront_window'); ?>
                            Datatyper
                        </a>
                    </li>
                    <li id="dock_FKSYS003">
                        <a href="#window_FKSYS003">
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_resize.png', 'Resize', 'resize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_minimize.png', 'Minimize', 'minimize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_tofront.png', 'To front', 'tofront_window'); ?>
                            Bloktyper
                        </a>
                    </li>
                    <li id="dock_FKSYS004">
                        <a href="#window_FKSYS004">
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_resize.png', 'Resize', 'resize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_minimize.png', 'Minimize', 'minimize_window'); ?>
                            <?= Utilities\HTML::LoadImage('Icons/icon_24_tofront.png', 'To front', 'tofront_window'); ?>
                            Bloktyper
                        </a>
                    </li>
                    <li id="dock_drive">
                        <a href="#window_drive">
                            <!--<?= Utilities\HTML::LoadImage('Icons/icon_22_drive.png'); ?>-->
                            Hard Drive
                        </a>
                    </li>
                    <li id="dock_disc">
                        <a href="#window_disc">
                            <!--<?= Utilities\HTML::LoadImage('Icons/icon_22_disc.png'); ?>-->
                            Audio CD
                        </a>
                    </li>
                    <li id="dock_network">
                        <a href="#window_network">
                            <!--<?= Utilities\HTML::LoadImage('Icons/icon_22_network.png'); ?>-->
                            Network
                        </a>
                    </li>
                </ul>
            </div>
        </div>

