<div class="abs" id="menubar">
    <span class="float_right" id="clock"></span>
    <ul>
        <li>
            <a class="menu_trigger" href="#">Kalna FormKit</a>
            <ul class="menu">
                <li>
                    <a class="punkt" href="#dock_computer">Computer</a>
                </li>
            </ul>
        </li>
        <li>
            <a class="menu_trigger" href="#">Rediger</a>
            <ul class="menu">
                <li>
                    <a class="punkt" href="#undo">Fortryd<span class="symbol">⌥⌘Z</span></a>
                </li>
                <li>
                    <a class="punkt" href="#redo">Gentag<span class="symbol">⇧⌥⌘Z</span></a>
                </li>
            </ul>
        </li>
        <li>
            <a class="menu_trigger" href="#">Ops&aelig;tning</a>
            <ul class="menu">
                <li>
                    <a class="punkt" href="#dock_applikation">Applikation</a>
                </li>
                <li>
                    <a class="punkt" href="#dock_modul">Modul<span class="symbol">⌥⌘⎋</span></a>
                </li>
                <li>
                    <a class="submenu_trigger" href="#">Data<span class="symbol">></span></a>
                    <ul class="submenu">
                        <li>
                            <a class="subpunkt" href="#dock_model">Model</a>
                        </li>
                        <li>
                            <a class="subpunkt" href="#dock_kollektion">Kollektion</a>
                        </li>
                        <li>
                            <a class="subpunkt" href="#dock_element">Element</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a class="submenu_trigger" href="#">Layout<span class="symbol">></span></a>
                    <ul class="submenu">
                        <li>
                            <a class="subpunkt" href="#dock_form">Form</a>
                        </li>
                        <li>
                            <a class="subpunkt" href="#dock_blok">Blok</a>
                        </li>
                        <li>
                            <a class="subpunkt" href="#dock_felt">Felt</a>
                        </li>
                        <li>
                            <a class="subpunkt" href="#dock_resource">Resource</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <a class="menu_trigger" href="#">System</a>
            <ul class="menu">
                <li>
                    <a class="punkt" href="SYS001">Datatyper</a>
                </li>
                <li>
                    <a class="punkt" href="SYS002">Felttyper</a>
                </li>
                <li>
                    <a class="punkt" href="SYS003">Feltskabeloner</a>
                </li>
                <li>
                    <a class="punkt" href="SYS004">Bloktyper</a>
                </li>
                <li>
                    <a class="punkt" href="SYS005">Egenskabtyper</a>
                </li>
                <li>
                    <a class="punkt" href="SYS005">Pr&aelig;fix koder</a>
                </li>
            </ul>
        </li>
        <li>
            <a class="menu_trigger" href="#">Hj&aelig;lp</a>
            <ul class="menu">
                <li>
                    <a class="punkt" href="#dock_shortcuts">Tastaturgenveje</a>
                </li>
                <li>
                    <a class="punkt" href="#dock_news">Nyheder i FormKit</a>
                </li>
                <li>
                    <a class="punkt" href="#dock_about">Om FormKit</a>
                </li>
            </ul>
        </li>
    </ul>
</div>