<div class="abs" id="toolbar">
    <ul>
        <li>
            <a class="menu_trigger" href="#">Kalna FormKit</a>
        </li>
        <li>
            <a class="menu_trigger" href="#">Rediger</a>
        </li>
        <li>
            <a class="menu_trigger" href="#">Ops&aelig;tning</a>
        </li>
        <li>
            <a class="menu_trigger" href="#">System</a>
        </li>
        <li>
            <a class="menu_trigger" href="#">Hj&aelig;lp</a>
        </li>
    </ul>
</div>