<div class="container">
    <div>
        <div class="row">
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Opgørelse</h3>
                <div class="row">
                    <div class="col col-md-6 col-head">Opgjort pr.</div>
                    <div class="col col-md-6">01-07-2014</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Hovedstol</div>
                    <div class="col col-md-6 text-right">120.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Renter</div>
                    <div class="col col-md-6 text-right">14.850,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Salær og omkost.</div>
                    <div class="col col-md-6 text-right">3.600,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Udlæg og gebyr</div>
                    <div class="col col-md-6 text-right">10.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Indbetalt</div>
                    <div class="col col-md-6 text-right">5.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Indb. til kreditor</div>
                    <div class="col col-md-6 text-right">0,00</div>
                </div>
                <div class="row row-line-top row-line-bottom-double">
                    <div class="col col-md-6 col-head">Restgæld</div>
                    <div class="col col-md-6 text-right">143.450,00</div>
                </div>
            </div>
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Debitoroplysninger</h3>
                <div class="row">
                    <div class="col col-md-5 col-head">Navn</div>
                    <div class="col col-md-7">Anders Fauntleroy And</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Adresse</div>
                    <div class="col col-md-7">Paradisæblevej 111<br>
                        92803 Andeby, Calisota</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Telefonnr.</div>
                    <div class="col col-md-7">33 45 67 89</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Mobilnr.</div>
                    <div class="col col-md-7">20 12 85 62</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">E-mailadresse</div>
                    <div class="col col-md-7">duck@disney.com</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">RKI</div>
                    <div class="col col-md-7">Indberettet</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Debitor Registret</div>
                    <div class="col col-md-7">Registreret</div>
                </div>
            </div>
            <div class="col-sm-5 col-md-12 box-standard first-col-head">
                <h3 class="">Sagsbeskrivelse</h3>
                <div class="row">
                    <div>Dermed kan der afsluttes uden løse ender, og de kan optimeres fra oven af at formidles stort uden brug fra presse. I en kant af landet går der blandt om, at de vil sætte den over forbehold for tiden. Vi flotter med et hold, der vil rundt og se sig om i byen. Det gør heller ikke mere. Men hvor vi nu overbringer denne størrelse til det den handler om, så kan der fortælles op til 3 gange.</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 box-standard first-col-head">
                <h3 class="">Fordringsoplysninger</h3>
                <div class="row">
                    <div class="col col-md-2 col-head">Forløb</div>
                    <div class="col col-md-7">1</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Status</div>
                    <div class="col col-md-7">Fogedretlig behandling indledes d. 26-06-2014</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Berammelse</div>
                    <div class="col col-md-7">02-07-2014</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Afdragsordning</div>
                    <div class="col col-md-7">Aktiv</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Afdragsbeløb</div>
                    <div class="col col-md-7">5.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Første termin</div>
                    <div class="col col-md-7">01-04-2014</div>
                </div>
                <div class="row">
                    <div class="col col-md-2 col-head">Antal terminer pr. år</div>
                    <div class="col col-md-7">12</div>
                </div>
                <div class="row">
                    <div class="box-standard underlined">
                        <h3 class="">Fakturaoplysninger
                        </h3>
                        <div class="row row-head">
                            <div class="col col-md-3">Faktura</div>
                            <div class="col col-md-2">Fakturabeløb</div>
                            <div class="col col-md-3">Rente</div>
                            <div class="col col-md-2">Doms/fundaments dato</div>
                            <div class="col col-md-2">Doms/fundaments beløb</div>
                        </div>
                        <div class="row">
                            <div class="col col-md-3">Fakturanr 5468 af d. 26-01-2014</div>
                            <div class="col col-md-2">100.000,00</div>
                            <div class="col col-md-3">Procesrente fra d. 26-02-2014</div>
                            <div class="col col-md-2">21-05-2014</div>
                            <div class="col col-md-2">100.000,00</div>
                        </div>
                        <div class="row">
                            <div class="col col-md-3">Fakturanr 5497 af d. 07-02-2014</div>
                            <div class="col col-md-2">20.000,00</div>
                            <div class="col col-md-3">Procesrente fra d. 07-03-2014</div>
                            <div class="col col-md-2">21-05-2014</div>
                            <div class="col col-md-2">20.000,00</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>