<div class="container">
    <div>
        <div class="row">
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Opgørelse</h3>
                <div class="row">
                    <div class="col col-md-6 col-head">Opgjort pr.</div>
                    <div class="col col-md-6">01-07-2014</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Hovedstol</div>
                    <div class="col col-md-6 text-right">120.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Renter</div>
                    <div class="col col-md-6 text-right">14.850,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Salær og omkost.</div>
                    <div class="col col-md-6 text-right">3.600,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Udlæg og gebyr</div>
                    <div class="col col-md-6 text-right">10.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Indbetalt</div>
                    <div class="col col-md-6 text-right">5.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-6 col-head">Indb. til kreditor</div>
                    <div class="col col-md-6 text-right">0,00</div>
                </div>
                <div class="row row-line-top row-line-bottom-double">
                    <div class="col col-md-6 col-head">Restgæld</div>
                    <div class="col col-md-6 text-right">143.450,00</div>
                </div>
            </div>
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Betaling</h3>
                <div class="row">
                    <div class="col">Betal med blandt andet Dankort og VISA-kort.</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Beløb</div>
                    <div class="col col-md-6"><input type="text" value=""></div>
                    <div class="col col-md-1 col-head">kr.</div>
                </div>
                <div class="row">
                    <div class="col">Betaling sker igennem ePay der er en sikker betalingsløsning der er godkendt af Nets og Teller.</div>
                </div>
                <div class="row">
                    <div class="col col-md-8"><img src="/InkassoPortal/Public/Images/gfx-kreditkort.png" width="170" height="31"></div>
                    <div class="col col-md-4 text-right">
                        <button type="button" class="callToAction">
                            Betal
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>