<div class="container">
    <div>
        <div class="row">
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Sagsoplysninger</h3>
                <div class="row">
                    <div class="col col-md-5 col-head">Vedrørende</div>
                    <div class="col col-md-7">Manglende afdrag på bil</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Hovedstol</div>
                    <div class="col col-md-7">120.000,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Restgæld</div>
                    <div class="col col-md-7">143.450,00</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Status</div>
                    <div class="col col-md-7">Afdragsordning</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Ansvarlig</div>
                    <div class="col col-md-7">Hans Spareby</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Jurist</div>
                    <div class="col col-md-7">Inkasso</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Sekretær</div>
                    <div class="col col-md-7">Inkasso</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Registreringsdato</div>
                    <div class="col col-md-7">09-06-2014</div>
                </div>
            </div>
            <div class="col-sm-5 col-md-4 box-standard first-col-head">
                <h3 class="">Debitoroplysninger</h3>
                <div class="row">
                    <div class="col col-md-5 col-head">Navn</div>
                    <div class="col col-md-7">Anders Fauntleroy And</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Adresse</div>
                    <div class="col col-md-7">Paradisæblevej 111<br>
                        92803 Andeby, Calisota</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Telefonnr.</div>
                    <div class="col col-md-7">33 45 67 89</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">Mobilnr.</div>
                    <div class="col col-md-7">20 12 85 62</div>
                </div>
                <div class="row">
                    <div class="col col-md-5 col-head">E-mailadresse</div>
                    <div class="col col-md-7">duck@disney.com</div>
                </div>
                <div class="row">
                    <div class="col col-md-8"></div>
                    <div class="col col-md-4 text-right">
                        <button type="button" class="callToAction">
                            Opdater
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="box-standard underlined box-hi4">
                <h3 class="">Sagsforløb
                </h3>
                <div class="row row-head">
                    <div class="col col-md-1">Reg.dato</div>
                    <div class="col col-md-5">Tekst</div>
                    <div class="col col-md-6">Dokument / Behandling</div>
                </div>
                <div class="row">
                    <div class="col col-md-1">09-07-2014</div>
                    <div class="col col-md-5">I en kant af landet går der blandt om, at de vil sætte den over forbehold for tiden</div>
                    <div class="col col-md-6"><span class="file task"></span></div>
                </div>
                <div class="row">
                    <div class="col col-md-1">06-07-2014</div>
                    <div class="col col-md-5">Dokument modtaget fra kreditor</div>
                    <div class="col col-md-6"><span class="file task2">Behandlet d. 09-07-2014</span></div>
                </div>
                <div class="row">
                    <div class="col col-md-1">06-07-2014</div>
                    <div class="col col-md-5">Dokument modtaget fra kreditor</div>
                    <div class="col col-md-6"><a href="Faktura_456321.pdf" class="file pdf">Faktura_456321.pdf</a></div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 box-standard underlined box-hi4">
                <h3 class="">Sagsnoter
                </h3>
                <div class="row row-head">
                    <div class="col col-md-2">Reg.dato<br>Initialer</div>
                    <div class="col col-md-10">Notat</div>
                </div>
                <div class="row">
                    <div class="col col-md-2">08-07-2014<br>BMK</div>
                    <div class="col col-md-10">Hvis det er træet til dit bord der får dig op, er det snarere varmen over de andre.</div>
                </div>
                <div class="row">
                    <div class="col col-md-2">06-07-2014<br>LKK</div>
                    <div class="col col-md-10">Det går der så nogle timer ud, hvor det er indlysende, at virkeligheden bliver tydelig istandsættelse.</div>
                </div>
                <div class="row">
                    <div class="col col-md-2">06-07-2014<br>LKK</div>
                    <div class="col col-md-10">Det er opmuntrende og anderledes, at det er dampet af kurset i morgen. Der indgives hvert år enorme strenge af blade af større eller mindre tilsnit.</div>
                </div>
                <div class="row">
                    <div class="col col-md-10"><textarea></textarea></div>
                    <div class="col-md-2 text-right">
                        <button type="button" class="callToAction">
                        Tilføj notat
                    </button>
                    </div>
                </div>
            </div>
            <div class="col-md-5 box-standard underlined box-hi4">
                <h3 class="">Dokumenter
                </h3>
                <div class="row row-head">
                    <div class="col col-md-3">Reg.dato</div>
                    <div class="col col-md-9">Dokument</div>
                </div>
                <div class="row">
                    <div class="col col-md-3">06-07-2014</div>
                    <div class="col col-md-9"><a href="Faktura_456321.pdf" class="file pdf">Faktura_456321.pdf</a></div>
                </div>
                <div class="row">
                    <div class="col col-md-9"><input type="file"></div>
                    <div class="col-md-3 text-right">
                        <button type="button" class="callToAction">
                        Tilføj fil
                    </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>