<div class='cover'>
    <div class="inner"><h1>Settings</h1></div>
</div>
<div class='container'>
    <div class='inner'>
        <section class='page'>
            <div class='settings-wrapper'>
                <nav>
                    <ul>
                        <li class="profile"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Profile">Your profile</a></li>
                        <li class="sessions active"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Sessions">Active sessions</a></li>
                        <li class="settings"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Settings">Organization</a></li>
                        <li class="users"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Users">Users</a></li>
                        <li class="clients"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Clients">Clients</a></li>
                        <li class="subscription"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Subscription">Plans &amp; billing</a></li>
                        <li class="receipts"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Receipts">Receipts</a></li>
                    </ul>

                </nav>
                <div class='content '>
                    <div class='page-header'>
                        <h1>Active sessions</h1>
                    </div>
                    <p>
                        These are the devices that are logged into your account. If you forgot to sign out on a shared/public device you can do so here.
                    </p>
                    <p>
                        A session will expire after two weeks without activity.
                    </p>
                    <ol class='sessions'>
                        <li data-user-session=''>
                            <div class='location'>
                                <span class='location'>Unknown location</span>
                            </div>
                            <div class='ip'>
                                2.108.208.60
                            </div>
                            <div class='browser source'><span class="browser-name">Firefox</span> on <span class="os-name">OS X 10.9</span></div>
                            <div class='created'>
                                Signed in on 04 September 2014 – 18:55
                            </div>
                            <span class='current-session'>Current<br> session</span>
                        </li>
                        <li data-user-session=''>
                            <div class='location'>
                                <span class='location'>Unknown location</span>
                            </div>
                            <div class='ip'>
                                2.108.208.60
                            </div>
                            <div class='browser source'><span class="browser-name">Firefox</span> on <span class="os-name">OS X 10.9</span></div>
                            <div class='accessed'>
                                Last activity on 01 September 2014 – 22:43
                            </div>
                            <div class='created'>
                                Signed in on 01 September 2014 – 21:54
                            </div>
                            <a class="button" data-session-type="browser" data-sign-out="" data-url="/sessions/3675" href="#">Sign out</a>
                        </li>
                        <li data-user-session=''>
                            <div class='location'>
                                <span class='location'>Unknown location</span>
                            </div>
                            <div class='ip'>
                                193.3.61.244
                            </div>
                            <div class='browser source'><span class="browser-name">Firefox</span> on <span class="os-name">Windows 7</span></div>
                            <div class='accessed'>
                                Last activity on 01 September 2014 – 16:36
                            </div>
                            <div class='created'>
                                Signed in on 26 August 2014 – 12:19
                            </div>
                            <a class="button" data-session-type="browser" data-sign-out="" data-url="/sessions/3588" href="#">Sign out</a>
                        </li>
                    </ol>
                </div>
            </div>

        </section>
        <section class='time-tracker' data-time-tracker=''>
            <div class='tab-bar' data-tab-switcher=''>
                <a class='active' href='#'>Log time</a>
                <a class='timer' href='#'>Timer</a>
            </div>
            <div class='tabs' data-tabs=''>
                <div class='active log-time tab'>
                    <div class='form-wrapper' data-logger=''>
                        <form accept-charset="UTF-8" action="/entries" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="iBVahSp7wwiAL/hPQBG1BVYPBkgi9P2uKmiJh0ARb9M=" /></div><div class='time-and-date'>
                                <div class='time'>
                                    <input class="time" id="entry_time" name="entry[time]" tabindex="1" type="text" />
                                </div>
                                <div class='date' data-date-picker=''>
                                    <input id="entry_date" name="entry[date]" type="hidden" value="today" />
                                    <a class='opener' data-opener='' href='#' tabindex='2'>
                                        <span data-label=''>Today</span>
                                    </a>
                                </div>
                            </div>
                            <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"}]'>
                                <input data-id-field="" id="entry_project_id" name="entry[project_id]" type="hidden" value="5020" />
                                <a class='opener' data-opener='' href='#'>
                                    <span class='client-name'>test</span>
                                    <span class='project-name'>test</span>
                                </a>
                            </div>

                            <div class='comment'>
                                <textarea data-behaviour="textarea_autogrow" id="entry_comment" name="entry[comment]" placeholder="Optional comment" tabindex="4">
                                </textarea>
                            </div>
                            <div class='actions'>
                                <button class="submit-button disabled" name="button" tabindex="5" type="submit">Log time</button>
                            </div>
                        </form>

                    </div>
                </div>
                <div class='tab timer' data-timer=''>
                    <div class='time'>
                        <div class='elapsed-time' data-time-field=''>
                            <span class='hours'>00</span>
                            <span class='separator'>:</span>
                            <span class='minutes'>00</span>
                            <span class='separator'>:</span>
                            <span class='seconds'>00</span>
                        </div>
                        <a class='play toggle-timer' data-toggle-timer='' href='#'></a>
                    </div>
                    <div class='spent-on'>
                        <span>Spent working on</span>
                    </div>
                    <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"}]'>
                        <input data-id-field="" id="timer_project_id" name="timer_project_id" type="hidden" value="5020" />
                        <a class='opener' data-opener='' href='#'>
                            <span class='client-name'>test</span>
                            <span class='project-name'>test</span>
                        </a>
                    </div>

                    <div class='comment'>
                        <textarea data-comment-field="" id="comment" name="comment" placeholder="Optional comment">
                        </textarea>
                    </div>
                    <div class='actions'>
                        <a class="button" data-delete="" href="#"><i class='icon-delete'></i>
                        </a><a class="button" data-finish="" href="#"><i class='icon-finish'></i>
                        </a></div>
                </div>
            </div>
            <div class='notifications' data-time-tracker-notifications=''></div>
        </section>

    </div>
</div>