<div class='cover'>
    <div class="inner"><h1>Settings</h1></div>
</div>
<div class='container'>
    <div class='inner'>
        <section class='page'>
            <div class='settings-wrapper'>
                <nav>
                    <ul>
                        <li class="profile"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Profile">Your profile</a></li>
                        <li class="sessions"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Sessions">Active sessions</a></li>
                        <li class="settings"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Settings">Organization</a></li>
                        <li class="users"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Users">Users</a></li>
                        <li class="clients"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Clients">Clients</a></li>
                        <li class="subscription active"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Subscription">Plans &amp; billing</a></li>
                        <li class="receipts"><a href="/<?= $this->appConfig->values['application']['path']; ?>/<?= $this->view; ?>/Receipts">Receipts</a></li>
                    </ul>

                </nav>
                <div class='content create-subscription'>
                    <div class='page-header'>
                        <h1>Plans & billing</h1>
                    </div>

                    <p>You have <b>20 days</b> left of your trial.
                        To keep on using Ding after this, pick a plan and enter your payment details. You will not be
                        charged until your trial period ends on
                        <b>September 28th, 2014</b>.</p>

                    <form accept-charset="UTF-8" action="/subscription" data-credit-card-form="" data-encryption-key="MIIBCgKCAQEAoBNT5rYY/UX+BiyTvA/0KFpgm5fARuGzAPnH8vRzbfCQ0ydiCLsd+Ao3BP/tHUebED/q8WYsMdG3DODw8Cn/YRkhJFaY9fY+to29KHC3uMpcbSA8DctsNTb/jZlwIwQ9lwsg9ZCNSQsGLs5V+4OsPQzPoeZTPhHRTHz0fZS1o1D/lQPcYzL6YCZRaP5PWRJQ7nqA8dFIQ+52ytkBHJvqmirJfn04K3RStHylDOnm5VPg7XxaePjZwOIeWNiZuRxDm/JiRHlv4d4FHI4MgpC34nSnybiTkQ6RVUgZTu9bBSGmBPV4Ne26ItAMeYdO71Jd5oupclPJScMxs2WfbZTpKQIDAQAB" data-redirect-to="/subscription" method="post" novalidate="novalidate"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="iBVahSp7wwiAL/hPQBG1BVYPBkgi9P2uKmiJh0ARb9M=" /></div><div class='plan-picker' data-plan-picker-mode='set_value' data-plan-picker=''>
                            <h2>1. Pick a plan</h2>
                            <input id="subscription_subscription_plan_id" name="subscription[subscription_plan][id]" type="hidden" value="" />
                            <ul class='plans'>
                                <li class='plan plan-solo ' data-id='4'>
                                    <div class='inner'>
                                        <div class='name'>Solo</div>
                                        <div class='price'>$10 <span class='month'>/ month</span></div>
                                        <ul class='features'>
                                            <li class='users'>
                                                1 user
                                            </li>
                                            <li class='clients'>Unlimited clients</li>
                                            <li class='projects'>Unlimited projects</li>
                                        </ul>
                                        <a class='button ' data-id='4' data-pick='' href='#'>
                                            Choose plan
                                        </a>
                                    </div>
                                </li>
                                <li class='plan plan-team ' data-id='5'>
                                    <div class='inner'>
                                        <div class='name'>Team</div>
                                        <div class='price'>$25 <span class='month'>/ month</span></div>
                                        <ul class='features'>
                                            <li class='users'>
                                                Unlimited users
                                            </li>
                                            <li class='clients'>Unlimited clients</li>
                                            <li class='projects'>Unlimited projects</li>
                                        </ul>
                                        <a class='button ' data-id='5' data-pick='' href='#'>
                                            Choose plan
                                        </a>
                                    </div>
                                </li>
                            </ul>

                        </div>
                        <div class='payment-method inactive'>
                            <h2>2. Enter payment details</h2>
                            <p>
                                Your payment information is securely stored at <a href="https://www.braintreegateway.com/merchants/936kf4hdq3pjn5tt/verified" target="blank">Braintree</a>.
                            </p>
                            <p>
                                Your subscription will be billed on September 28th, 2014
                            </p>
                            <div class='credit-card-form'>
                                <div class='logo'></div>
                                <div class='card-number'>
                                    <label for="subscription_credit_card_number">Card number</label>
                                    <div class="form-field text-field" data-field-name="number"><input disabled="disabled" id="subscription_credit_card_number" name="subscription[credit_card][number]" pattern="\d*" type="text" value="" /></div>
                                </div>
                                <div class='expiration-date'>
                                    <label for="subscription_credit_card_expiration_month">Expiration date</label>
                                    <div class='fields'>
                                        <div class="form-field text-field" data-field-name="expiration_month"><input disabled="disabled" id="subscription_credit_card_expiration_month" label="false" name="subscription[credit_card][expiration_month]" pattern="\d*" placeholder="mm" type="text" value="" /></div>
                                        <div class="form-field text-field" data-field-name="expiration_year"><input disabled="disabled" id="subscription_credit_card_expiration_year" label="false" name="subscription[credit_card][expiration_year]" pattern="\d*" placeholdeR="yy" type="text" value="" /></div>
                                    </div>
                                </div>
                                <div class='cvv'>
                                    <label for="subscription_credit_card_cvv">CVV Code</label>
                                    <div class="form-field text-field" data-field-name="cvv"><input disabled="disabled" id="subscription_credit_card_cvv" name="subscription[credit_card][cvv]" pattern="\d*" type="text" value="" /></div>
                                    <a class='help'></a>
                                </div>
                            </div>

                            <div class='form-row'>
                                <a class="button button-save" data-submit="" href="#">Start subscription</a>
                            </div>
                        </div>
                    </form>


                </div>
            </div>

        </section>
        <section class='time-tracker' data-time-tracker=''>
            <div class='tab-bar' data-tab-switcher=''>
                <a class='active' href='#'>Log time</a>
                <a class='timer' href='#'>Timer</a>
            </div>
            <div class='tabs' data-tabs=''>
                <div class='active log-time tab'>
                    <div class='form-wrapper' data-logger=''>
                        <form accept-charset="UTF-8" action="/entries" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="iBVahSp7wwiAL/hPQBG1BVYPBkgi9P2uKmiJh0ARb9M=" /></div><div class='time-and-date'>
                                <div class='time'>
                                    <input class="time" id="entry_time" name="entry[time]" tabindex="1" type="text" />
                                </div>
                                <div class='date' data-date-picker=''>
                                    <input id="entry_date" name="entry[date]" type="hidden" value="today" />
                                    <a class='opener' data-opener='' href='#' tabindex='2'>
                                        <span data-label=''>Today</span>
                                    </a>
                                </div>
                            </div>
                            <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"}]'>
                                <input data-id-field="" id="entry_project_id" name="entry[project_id]" type="hidden" value="5020" />
                                <a class='opener' data-opener='' href='#'>
                                    <span class='client-name'>test</span>
                                    <span class='project-name'>test</span>
                                </a>
                            </div>

                            <div class='comment'>
                                <textarea data-behaviour="textarea_autogrow" id="entry_comment" name="entry[comment]" placeholder="Optional comment" tabindex="4">
                                </textarea>
                            </div>
                            <div class='actions'>
                                <button class="submit-button disabled" name="button" tabindex="5" type="submit">Log time</button>
                            </div>
                        </form>

                    </div>
                </div>
                <div class='tab timer' data-timer=''>
                    <div class='time'>
                        <div class='elapsed-time' data-time-field=''>
                            <span class='hours'>00</span>
                            <span class='separator'>:</span>
                            <span class='minutes'>00</span>
                            <span class='separator'>:</span>
                            <span class='seconds'>00</span>
                        </div>
                        <a class='play toggle-timer' data-toggle-timer='' href='#'></a>
                    </div>
                    <div class='spent-on'>
                        <span>Spent working on</span>
                    </div>
                    <div class='project' data-clients='[{"id":3468,"name":"Lund Elmer Sandager"},{"id":3391,"name":"test"}]' data-last-project='{"id":5020,"name":"test","client":"test"}' data-project-picker='' data-projects='[{"id":5184,"name":"Konsulentbistand","client":"Lund Elmer Sandager"}]'>
                        <input data-id-field="" id="timer_project_id" name="timer_project_id" type="hidden" value="5020" />
                        <a class='opener' data-opener='' href='#'>
                            <span class='client-name'>test</span>
                            <span class='project-name'>test</span>
                        </a>
                    </div>

                    <div class='comment'>
                        <textarea data-comment-field="" id="comment" name="comment" placeholder="Optional comment">
                        </textarea>
                    </div>
                    <div class='actions'>
                        <a class="button" data-delete="" href="#"><i class='icon-delete'></i>
                        </a><a class="button" data-finish="" href="#"><i class='icon-finish'></i>
                        </a></div>
                </div>
            </div>
            <div class='notifications' data-time-tracker-notifications=''></div>
        </section>

    </div>
</div>