<!doctype html>
<html lang="da">
    <head>
        <meta charset="UTF-8">
        <meta name="description" content="InkassoPortal giver dig overblik">
        <meta name="section" content="<?= $this->view ?>"
        <meta name="author" content="Kalna">
        <meta name="viewport" content="width=device-width">
        
        <title>InkassoPortal <?= $this->view ?></title>
        
        <!--[if lt IE 9]>
            <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js" />
        <![endif]-->
    </head>
    <body>
        
    </body>
</html>
